### ISSUE TITLE
[Bug] Go to the first unread comment is not working

### ISSUE THREAD

**Issue by gizellos** [revilheart/ESGST#134]
The icon link "Go to the first unread comment" in the list of threads is not working for me. It takes me always to the same read comment.

The link to the first unread comment in topics themselves worked well yesterday when I tested this issue, but today, it doesn't do anything (there was not a new version, though).

I enclosed a gif. You can see there that there should have been 1 unread comment but it took me to a 2 days old comment of mine that is read.

![last unread comment](https://cloud.githubusercontent.com/assets/2397851/26526646/e02518ca-4381-11e7-8262-e516007874e5.gif)

**Comment by gizellos** [comment]
I think that also the button for marking all as read doesn't work as it should. Marking 1 comments takes the script several tens of seconds, which is quite a lot, according to the fact that I have fast internet and after the process, the text doesn't refresh so it still shows the amount of unread comments although there already are not any.

![2017-05-28_101025](https://cloud.githubusercontent.com/assets/2397851/26527181/56c102ee-438e-11e7-9f3a-c114dc8c8aae.png)

**Comment by gizellos** [comment]
I think it may be the the same issue as @ideman somewhere mentioned that it shows one more comments (that doesn't exist). It can be the reason why it doesn't work inside the topic.

**Comment by ldeman** [comment]
showing one less* comment, but yea.  there's a lot of funky stuff going on with the comment tracking since 6beta3.6/6beta3.7 range.

**Comment by gizellos** [comment]
@Ideman OK, less. I tested the feature a bit and it seems quite random. Sometime it is working and sometime is not.

But I don't use it regularly,  you are a better tester for it since you use it all time.

**Comment by ldeman** [comment]
@gizellos yeah it does seem very random, it only appears to do that on certain topics. others it works just perfectly on.  but it does seem to be the same topics it does it on over and over,  so it's not entirely random, but i haven't a clue what's triggering it to do that.

**Comment by revilheart** [comment]
I'll rewrite the Comment Tracker feature later this week.

**Comment by revilheart** [comment]
Should be fixed, let me know if not.

**Comment by ldeman** [comment]
>Should be fixed, let me know if not.

the "showing 1less comment" part is still happening.  ESGST thread showed it only had one unread comment inside of it, but it actually had 2 unread comments.  (both actual comments/replies, unrelated to the op being read)

**Comment by gizellos** [comment]
It doesn't work, unfortunately. 1.) It opens the page in new tab (I hope it is not a feature, because new tabs sucks). 2.) It opens just the original page - it means no comments.

**Comment by gizellos** [comment]
![go to the last unread comment](https://user-images.githubusercontent.com/2397851/27035669-78cd174c-4f82-11e7-91d3-92e7eebab248.gif)

**Comment by ldeman** [comment]
@revilheart  "go to last unread comment" seems to work just fine, so maybe a comparison can be done in the code to see what's different about it versus "go to first unread comment".  ;)

**Comment by revilheart** [comment]
@ldeman Hmm I'll have to check that out later.

@gizellos From the looks of it, the OP is not marked as read, since it's not faded out, so it's correctly bringing you to the first unread comment. As to it opening in a new tab, it's a functionality (why do people always assume that things opening in a new tab is a bug? it's not possible for the script to open something in a new tab by itself, I have to code it :P). I'll remove it later.

**Comment by gizellos** [comment]
> why do people always assume that things opening in a new tab is a bug?

Because for some kind of links it doesn't make a sense to open them in a new tab. I wouldn't write that it is a bug if you opened in new tab a link leading outside SG (although I am not a fan of this either).  There is bread crumbs navigation on the forum, browser button Back, keyboad shorcuts, mouse buttons, and so on - there is really not a problem to get back to the previous list of links. This is how the internet pages work, you click on a link and you will get to the place.

**Comment by gizellos** [comment]
BTW maybe it would be good if you added and option for disabling the feature because (I guess) the visited OPs eat storage even for people who don't use the feature.

**Comment by revilheart** [comment]
Still, you shouldn't call it a bug as it is intended. "Behavior" is better.

But this script isn't the internet, and these aren't links (all links in the script open in the same tab, as far as I know, except for links to pages outside of SG, but SG itself does that). They are buttons that you can click on, which will start processing something and return the result of the process. If you want to process multiple stuff at the same time, opening the result in a new tab makes much more sense. Let's say you want to go to the first unread comment of 3 different discussions. If the result opens in the same tab, you won't be able to do that easily (you will have to do each discussion individually, which will take much more time). But if the result opens in a new tab, you can simply click the button in each discussion and wait for all of them to be found quickly and easily.

No, they don't. It only saves to the storage for people who have Comment Tracker enabled.

**Comment by gizellos** [comment]
I didn't call it a bug, I just hoped it was a bug. :) Ok, there are two kind of users, one needs it in new tabs and it is good for them and the other who don't need it and it is annoying for them.

It is bad that buttons or javascript links don't support right mouse button. :/ I hope it will be possible one day.

Either way an option for enabling/disabling the opening in new tab would satisfy everyone. :)

**Comment by revilheart** [comment]
It's not possible for them to support right mouse button, since they aren't links.

**Comment by gizellos** [comment]
They could do it for opening in new tabs at least. They could duplicate the page, click to the link and render it in a new tab. The same method like people do when they need it. Just the browser would do it in the background. For cases when the lino or button is not intended as a link leading to somewhere, it could be disabled by programmers.

**Comment by ldeman** [comment]
i think i got the confusion now on the "+1 or -1" confusion and why it's still showing incorrectly for me.

it's been happening everywhere instead of just on a few random threads.  so i think it's partially fixed, but i think it's registering the ops read comment as a regular comment so that's why it's not showing the correct "+1" unread comments.

and also i think that's why gizellos was seeing it as an opposite issue, everything was read comment wise, but the thread op wasn't being read and it was showing the +1 when they thought there weren't any unread comments.

it's that op comment counting or not counting as a +1 or not that is causing both confusion and the bug i believe.

**Comment by gizellos** [comment]
@ldeman Isn't it related to [this new issue](https://github.com/revilheart/ESGST/issues/159) by me?

**Comment by ldeman** [comment]
@gizellos i think so.

**Comment by revilheart** [comment]
If you weren't aware, it does show the OP as an unread comment. That has always been the behavior though. If a thread has 85 comments, it will show +86 unread if the OP is unread.

**Comment by ldeman** [comment]
@revilheart yes, i'm aware.  my issue is the opposite direction.  there isn't a "+1" registering on /discussions page when there should be.

**Comment by ldeman** [comment]
sorry, i probably should open up my own topic about this, but it's extremely relative.
but anyways... 
here's an example of the +1 not being there when it should be.  
![peek 2017-06-13 16-53](https://user-images.githubusercontent.com/10275898/27106506-42a7dd28-5059-11e7-820b-e8ccaed0ab6b.gif)
sorry for really slow internet during this gif creation - diff pc windows update =/

**Comment by revilheart** [comment]
Is this still a bug, by the way? If the OP is read, is it still always going to it?

**Comment by ldeman** [comment]
now this feature genuinely is bugging out for me on one specific topic.  (still works perfectly fine on all others for me though) -- i use this feature in reverse btw. (Search for first unread comment in reverse order (from newest to oldest).)
![peek 2017-06-15 08-17](https://user-images.githubusercontent.com/10275898/27183174-5d83f69a-51a3-11e7-95b3-045151d9d10f.gif)
no errors in console.

**Comment by ldeman** [comment]
i figured it out.   this feature isn't working with threads that are larger then 100pages, unless the unread comment happens to be on page 1.

**Comment by revilheart** [comment]
Ah, that's expected for reverse option, since there isn't a last page button in those threads. I'll have to tweak the reverse option to go forward in that case, and not backwards.

**Comment by ldeman** [comment]
>Ah, that's expected for reverse option, since there isn't a last page link in those threads. I'll have to tweak the reverse option to go forward in that case, and not backwards.

sounds good to me.  =)

**Comment by revilheart** [comment]
The last update should solve all issues related to this, so closing it. Let me know if it's not solved.
